---

- name: install nfs utils
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - nfs-common
    - autofs
    - rpcbind

- name: ensure rpcbind service is running
  service:
    name: rpcbind
    state: started
    enabled: yes
